# Generated by Django 5.2.11 on 2026-04-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_sale"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Мягко удалён"),
        ),
    ]
